# Generated by Django 4.0.5 on 2022-08-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Autor')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='author_photos', verbose_name='Foto del Autor')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Demography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demography', models.CharField(max_length=80, unique=True, verbose_name='Demografía')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
            ],
            options={
                'verbose_name': 'Demografía',
                'verbose_name_plural': 'Demografías',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=80, unique=True, verbose_name='Género')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Manga')),
                ('original_name', models.CharField(max_length=255, verbose_name='Nombre Original del Manga')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción/Sinopsis')),
                ('image', models.ImageField(upload_to='portadas', verbose_name='Portada del Manga')),
                ('year', models.CharField(max_length=6, verbose_name='Año')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio')),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('recommended_age', models.CharField(max_length=30, verbose_name='Edad Recomendada')),
                ('available', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.author', verbose_name='Autor')),
                ('demography', models.ManyToManyField(to='Store.demography')),
                ('genre', models.ManyToManyField(to='Store.genre')),
            ],
            options={
                'verbose_name': 'Manga',
                'verbose_name_plural': 'Mangas',
            },
        ),
    ]
