# Generated by Django 4.0.5 on 2022-08-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='description',
            field=models.CharField(max_length=555, verbose_name='Descripción/Sinopsis'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='price',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
