# Generated by Django 4.0.5 on 2022-08-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='To_Do_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título de la Tarea')),
                ('desc', models.CharField(max_length=555, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('done', models.BooleanField(default=False, verbose_name='¿Completada?')),
                ('removed_or_not', models.BooleanField(default=False, verbose_name='¿Eliminada?')),
            ],
            options={
                'verbose_name': 'Tareas',
            },
        ),
    ]
