# Generated by Django 4.0.5 on 2022-07-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='price',
            field=models.IntegerField(verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='section',
            field=models.CharField(max_length=20, verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='address',
            field=models.CharField(max_length=80, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Dirección Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='phone_number',
            field=models.CharField(max_length=100, verbose_name='Número de Teléfono'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(verbose_name='Fecha de Envío'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='number',
            field=models.IntegerField(verbose_name='Número de Pedido'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='received',
            field=models.BooleanField(verbose_name='¿Recibido?'),
        ),
    ]
