# Generated by Django 4.0.5 on 2022-09-05 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Categoría')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Console_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la Consola')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Consola',
                'verbose_name_plural': 'Consolas',
            },
        ),
        migrations.CreateModel(
            name='Genres_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Género del Juego')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Género del Juego',
                'verbose_name_plural': 'Géneros de los Juegos',
            },
        ),
        migrations.CreateModel(
            name='Posts_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título del Post')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images_posts', verbose_name='Imágen del Post')),
                ('content', models.TextField(blank=True, db_column='content', null=True, verbose_name='Contenido del Post')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('category', models.ManyToManyField(to='principal.category_model', verbose_name='Categorías')),
                ('console_name', models.ManyToManyField(to='principal.console_model', verbose_name='Consolas')),
                ('down_voted', models.ManyToManyField(related_name='dislikes', to=settings.AUTH_USER_MODEL)),
                ('genre', models.ManyToManyField(to='principal.genres_model', verbose_name='Géneros')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Publicado por')),
                ('up_voted', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Publicación',
                'verbose_name_plural': 'Publicaciones',
            },
        ),
        migrations.CreateModel(
            name='Comments_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=555, verbose_name='Comentario')),
                ('commented_on', models.DateTimeField(auto_now_add=True, verbose_name='Comentado el')),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentario de')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.posts_model', verbose_name='Título de la Publicación Comentada')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
