# Generated by Django 4.0.5 on 2022-07-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Nombre de Usuario')),
                ('first_name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=150, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=150, verbose_name='Contraseña')),
                ('image', models.ImageField(blank=True, null=True, upload_to='UsersImages', verbose_name='Imagen de Usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es Activo?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='¿Es Staff?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Usuario Creado el')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
    ]
