# Generated by Django 4.0.5 on 2022-07-15 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Store', '0003_alter_categoryproduct_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Pedido Creado el')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id del Usuario')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'db_table': 'Orders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OrdersApp.order', verbose_name='id del Pedido')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.product', verbose_name='id del Producto')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='id del Usuario')),
            ],
            options={
                'verbose_name': 'Línea del Pedido',
                'verbose_name_plural': 'Líneas de los Pedidos',
                'db_table': 'OrderLine',
                'ordering': ['id'],
            },
        ),
    ]
