# Generated by Django 4.0.5 on 2022-07-13 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre de la Categoría')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Actualizado el')),
            ],
            options={
                'verbose_name': 'Categorías del Producto',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre del Producto')),
                ('price', models.FloatField(verbose_name='Precio')),
                ('image', models.ImageField(upload_to='Store', verbose_name='Imagen del Producto')),
                ('details', models.CharField(max_length=255, verbose_name='Detalles del Producto')),
                ('sold', models.BooleanField(default=False, verbose_name='¿Vendido?')),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.categoryproduct', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
