# Generated by Django 4.0.5 on 2022-07-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categorías de los Productos'},
        ),
    ]
